# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
alias la='ls -al'

PS1='\[\033[0;35m\]\h \[\033[0;32m\]\W \[\033[1;31m\]>\[\033[00m\] '
