# Created by newuser for 5.1.1
source ~/Code/.antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle command-not-found
antigen bundle pip

antigen bundle robbyrussell/oh-my-zsh
antigen bundle zsh-users/zsh-syntax-highlighting

antigen theme dflazz

antigen apply

